modLoader="javafml" #mandatory
loaderVersion="[28,]" #mandatory
license="GNU General Public License v3.0"
credits="" #optional
authors="gigabit101" #optional
[[mods]] #mandatory
    # The modid of the mod
    modId="quantumstorage" #mandatory
    # The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
    version="${file.jarVersion}" #mandatory
     # A display name for the mod
    displayName="QuantumStorage" #mandatory
    # The description text for the mod (multi line!) (#mandatory)
    description='''
'''

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16, 1.17]"
    ordering="NONE"
    side="BOTH"